apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kustomize-pipeline
spec:
  templates:
    - name: generate
      inputs:
        parameters:
          - name: iterations
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json
          import sys
          json.dump([i for i in range(1, {{inputs.parameters.iterations}})], sys.stdout)
