apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: general
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: general
subjects:
  - kind: ServiceAccount
    name: kustomize-pipeline
